use std::path::PathBuf;
use std::sync::OnceLock;
use tauri::{Manager, WebviewUrl, WebviewWindowBuilder};

/// Which daemon this app talks to, decided once at launch.
///
/// A packaged app (a .dmg or a Linux .deb/.AppImage) carries its own Node and
/// daemon and runs them itself. A dev build has neither, and on Linux talks to
/// the systemd unit running from the repo instead.
///
/// On Linux a packaged app is its own instance -- its own dirs and ports -- so
/// it can sit next to a dev setup without the two sharing bots, keys or a
/// database. On macOS there is only ever the packaged app, so it keeps the
/// defaults.
struct Instance {
    packaged: bool,
    config_dir: PathBuf,
    data_dir: PathBuf,
    runtime_dir: Option<PathBuf>,
    port: u16,
    hooks_port: u16,
}

static INSTANCE: OnceLock<Instance> = OnceLock::new();

fn instance() -> &'static Instance {
    INSTANCE.get().expect("instance is set in setup()")
}

fn init_instance(app: &tauri::AppHandle) {
    let home = PathBuf::from(std::env::var("HOME").unwrap_or_default());
    let packaged = daemon_paths(app).map(|(node, script)| node.exists() && script.exists()).unwrap_or(false);
    let inst = if cfg!(target_os = "macos") {
        // Must match the macOS dirs in packages/daemon/src/config.ts.
        let dir = home.join("Library/Application Support/Grokked");
        Instance { packaged, config_dir: dir.clone(), data_dir: dir, runtime_dir: None, port: 8787, hooks_port: 8788 }
    } else if packaged {
        let xdg = |var: &str, fallback: &str| {
            std::env::var(var).ok().filter(|v| v.starts_with('/')).map(PathBuf::from).unwrap_or_else(|| home.join(fallback))
        };
        Instance {
            packaged,
            config_dir: xdg("XDG_CONFIG_HOME", ".config").join("grokked-app"),
            data_dir: xdg("XDG_DATA_HOME", ".local/share").join("grokked-app"),
            runtime_dir: std::env::var("XDG_RUNTIME_DIR").ok().map(|d| PathBuf::from(d).join("grokked-app")),
            port: 8797,
            hooks_port: 8798,
        }
    } else {
        // The systemd unit's defaults. Must match packages/daemon/src/config.ts.
        Instance {
            packaged,
            config_dir: home.join(".config/grokked"),
            data_dir: home.join(".local/share/grokked"),
            runtime_dir: None,
            port: 8787,
            hooks_port: 8788,
        }
    };
    let _ = INSTANCE.set(inst);
}

/// The bundled Node (a sidecar next to the app binary) and daemon (a resource).
fn daemon_paths(app: &tauri::AppHandle) -> Result<(PathBuf, PathBuf), String> {
    let exe = std::env::current_exe().map_err(|e| e.to_string())?;
    let node = exe.parent().ok_or("no exe dir")?.join("grokked-node");
    let script = app.path().resource_dir().map_err(|e| e.to_string())?.join("daemon/grokked.mjs");
    Ok((node, script))
}

/// The daemon's bearer token, generated by the daemon on first boot.
/// The UI never stores credentials of its own.
#[tauri::command]
fn daemon_token() -> Result<String, String> {
    let path = instance().config_dir.join("token");
    std::fs::read_to_string(&path)
        .map(|s| s.trim().to_string())
        .map_err(|e| format!("could not read {}: {e}", path.display()))
}

/// Where the UI should find the daemon. Only the packaged Linux app moves it.
#[tauri::command]
fn daemon_url() -> String {
    format!("http://127.0.0.1:{}", instance().port)
}

/// The dev setup on Linux: a systemd user unit running from the repo.
#[cfg(target_os = "linux")]
mod systemd {
    pub fn is_running() -> bool {
        std::process::Command::new("systemctl")
            .args(["--user", "is-active", "grokked.service"])
            .output()
            .map(|o| String::from_utf8_lossy(&o.stdout).trim() == "active")
            .unwrap_or(false)
    }

    pub fn start() -> Result<(), String> {
        std::process::Command::new("systemctl")
            .args(["--user", "start", "grokked.service"])
            .status()
            .map_err(|e| e.to_string())
            .and_then(|s| if s.success() { Ok(()) } else { Err("systemctl start failed".into()) })
    }

    /// Last 40 journal lines. Debugging a daemon you cannot see is miserable,
    /// so the UI puts them one click away.
    pub fn logs() -> String {
        std::process::Command::new("journalctl")
            .args(["--user", "-u", "grokked", "-n", "40", "--no-pager", "-o", "cat"])
            .output()
            .map(|o| String::from_utf8_lossy(&o.stdout).to_string())
            .unwrap_or_else(|e| format!("could not read journal: {e}"))
    }
}

/// A packaged app runs the daemon itself, so nobody has to install a service
/// by hand. The trade-off is that bots stop when the app quits.
mod child {
    use std::io::{Read, Seek, SeekFrom};
    use std::process::{Child, Command, Stdio};
    use std::sync::Mutex;
    use tauri::Manager;

    pub struct Proc(pub Mutex<Option<Child>>);
    static START_ERROR: Mutex<Option<String>> = Mutex::new(None);

    fn log_path() -> std::path::PathBuf {
        super::instance().config_dir.join("daemon.log")
    }

    fn port_open() -> bool {
        std::net::TcpStream::connect_timeout(
            &std::net::SocketAddr::from(([127, 0, 0, 1], super::instance().port)),
            std::time::Duration::from_millis(300),
        )
        .is_ok()
    }

    pub fn is_running(app: &tauri::AppHandle) -> bool {
        let state = app.state::<Proc>();
        let mut guard = state.0.lock().unwrap();
        let alive = match guard.as_mut() {
            Some(c) => matches!(c.try_wait(), Ok(None)),
            None => false,
        };
        alive || port_open()
    }

    pub fn start(app: &tauri::AppHandle) -> Result<(), String> {
        if is_running(app) {
            return Ok(());
        }
        let r = spawn(app);
        *START_ERROR.lock().unwrap() = r.as_ref().err().cloned();
        r
    }

    fn spawn(app: &tauri::AppHandle) -> Result<(), String> {
        let inst = super::instance();
        let (node, script) = super::daemon_paths(app)?;
        std::fs::create_dir_all(&inst.config_dir).map_err(|e| e.to_string())?;
        let log = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(log_path())
            .map_err(|e| e.to_string())?;

        let mut cmd = Command::new(&node);
        cmd.arg(&script)
            .env("NODE_ENV", "production")
            // Tells the daemon to use the published bot computer image even if
            // a locally built one is around (see runtime/docker.ts).
            .env("GROKKED_PACKAGED", "1")
            .env("GROKKED_CONFIG_DIR", &inst.config_dir)
            .env("GROKKED_DATA_DIR", &inst.data_dir)
            .env("GROKKED_PORT", inst.port.to_string())
            .env("GROKKED_HOOKS_PORT", inst.hooks_port.to_string())
            .current_dir(&inst.config_dir)
            .stdin(Stdio::null())
            .stdout(log.try_clone().map_err(|e| e.to_string())?)
            .stderr(log);
        if let Some(dir) = &inst.runtime_dir {
            cmd.env("GROKKED_RUNTIME_DIR", dir);
        }
        let child = cmd.spawn().map_err(|e| format!("could not start {}: {e}", node.display()))?;
        *app.state::<Proc>().0.lock().unwrap() = Some(child);

        // The UI health-checks right after this returns; give the daemon a moment
        // to bind so "Start daemon" doesn't bounce straight back to the error.
        for _ in 0..50 {
            if port_open() {
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(100));
        }
        Ok(())
    }

    pub fn logs() -> String {
        let mut f = match std::fs::File::open(log_path()) {
            Ok(f) => f,
            Err(e) => return format!("could not read {}: {e}", log_path().display()),
        };
        let len = f.metadata().map(|m| m.len()).unwrap_or(0);
        let _ = f.seek(SeekFrom::Start(len.saturating_sub(8000)));
        let mut s = String::new();
        let _ = f.read_to_string(&mut s);
        s.lines().rev().take(40).collect::<Vec<_>>().into_iter().rev().collect::<Vec<_>>().join("\n")
    }

    /// Why the daemon isn't up, when we know: it failed to spawn, or it spawned
    /// and exited (the log tail says why). None while it's running.
    pub fn last_error(app: &tauri::AppHandle) -> Option<String> {
        let state = app.state::<Proc>();
        let mut guard = state.0.lock().unwrap();
        match guard.as_mut().map(|c| c.try_wait()) {
            Some(Ok(Some(status))) => Some(format!("The daemon exited ({status}). Show logs for why.")),
            _ => START_ERROR.lock().unwrap().clone(),
        }
    }

    /// SIGTERM, not kill(): the daemon checkpoints SQLite's WAL on the way out.
    pub fn stop(app: &tauri::AppHandle) {
        if let Some(mut c) = app.state::<Proc>().0.lock().unwrap().take() {
            let _ = Command::new("kill").args(["-TERM", &c.id().to_string()]).status();
            for _ in 0..50 {
                if !matches!(c.try_wait(), Ok(None)) {
                    return;
                }
                std::thread::sleep(std::time::Duration::from_millis(100));
            }
            let _ = c.kill();
        }
    }
}

/// Packaged apps manage a child daemon; a Linux dev build defers to systemd.
mod daemon {
    pub fn is_running(app: &tauri::AppHandle) -> bool {
        #[cfg(target_os = "linux")]
        if !super::instance().packaged {
            return super::systemd::is_running();
        }
        super::child::is_running(app)
    }

    pub fn start(app: &tauri::AppHandle) -> Result<(), String> {
        #[cfg(target_os = "linux")]
        if !super::instance().packaged {
            return super::systemd::start();
        }
        super::child::start(app)
    }

    pub fn logs() -> String {
        #[cfg(target_os = "linux")]
        if !super::instance().packaged {
            return super::systemd::logs();
        }
        super::child::logs()
    }

    pub fn last_error(app: &tauri::AppHandle) -> Option<String> {
        if super::instance().packaged {
            super::child::last_error(app)
        } else {
            None
        }
    }

    pub fn start_on_launch(app: &tauri::AppHandle) {
        if super::instance().packaged {
            if let Err(e) = super::child::start(app) {
                eprintln!("daemon did not start: {e}");
            }
        }
    }

    pub fn stop(app: &tauri::AppHandle) {
        if super::instance().packaged {
            super::child::stop(app);
        }
    }
}

#[tauri::command]
fn daemon_status(app: tauri::AppHandle) -> serde_json::Value {
    serde_json::json!({
        "unit_active": daemon::is_running(&app),
        "error": daemon::last_error(&app),
    })
}

#[tauri::command]
fn start_daemon(app: tauri::AppHandle) -> Result<(), String> {
    daemon::start(&app)
}

#[tauri::command]
fn daemon_logs() -> String {
    daemon::logs()
}

pub fn run() {
    // Serve the frontend over plain http://localhost instead of Tauri's custom
    // scheme. The custom scheme is treated as a secure context, which makes the
    // http://127.0.0.1:16080 noVNC iframe active mixed content -- WebKitGTK
    // blocks it and renders a blank frame with no console message.
    let port = portpicker::pick_unused_port().expect("no free port");

    tauri::Builder::default()
        .manage(child::Proc(std::sync::Mutex::new(None)))
        .plugin(tauri_plugin_localhost::Builder::new(port).build())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_clipboard_manager::init())
        .invoke_handler(tauri::generate_handler![
            daemon_token,
            daemon_url,
            daemon_status,
            start_daemon,
            daemon_logs
        ])
        .setup(move |app| {
            init_instance(app.handle());
            daemon::start_on_launch(app.handle());

            // tauri-plugin-localhost's server does not map the bare "/" -- it
            // answers 500 there while serving /index.html and /assets/* fine,
            // which renders as a blank white window with no error anywhere.
            // Ask for index.html explicitly.
            //
            // In dev, point at the vite server instead so HMR works. That is
            // already a plain http://localhost origin, so the mixed-content rule
            // that forces the localhost plugin in release does not apply.
            let url = if cfg!(debug_assertions) {
                option_env!("TAURI_DEV_URL")
                    .unwrap_or("http://localhost:1430")
                    .parse()
                    .unwrap()
            } else {
                // A page served from http://localhost is a *remote* origin to
                // Tauri, and remote origins get no IPC unless a capability names
                // them. Without this every invoke() fails in release builds only
                // (dev's URL is the configured devUrl, which counts as local), so
                // the token lookup and the Start daemon / Show logs buttons all
                // silently did nothing. Same permissions as capabilities/main.json.
                let mut cap = tauri::ipc::CapabilityBuilder::new("localhost")
                    .remote(format!("http://localhost:{port}/*"))
                    .window("main");
                for p in [
                    "core:default",
                    "opener:default",
                    "notification:default",
                    "clipboard-manager:allow-read-text",
                    "clipboard-manager:allow-write-text",
                    "allow-daemon-token",
                    "allow-daemon-url",
                    "allow-daemon-status",
                    "allow-start-daemon",
                    "allow-daemon-logs",
                ] {
                    cap = cap.permission(p);
                }
                app.add_capability(cap)?;
                format!("http://localhost:{port}/index.html").parse().unwrap()
            };
            WebviewWindowBuilder::new(app, "main", WebviewUrl::External(url))
                .title("Grokked Bot")
                .inner_size(1500.0, 950.0)
                .min_inner_size(1100.0, 700.0)
                .build()?;
            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|app, event| {
            if let tauri::RunEvent::Exit = event {
                daemon::stop(app);
            }
        });
}
