use tauri::{WebviewUrl, WebviewWindowBuilder};

/// The daemon's bearer token, generated by the daemon on first boot.
/// The UI never stores credentials of its own.
#[tauri::command]
fn daemon_token() -> Result<String, String> {
    let home = std::env::var("HOME").map_err(|e| e.to_string())?;
    let path = std::path::Path::new(&home).join(".config/grokked/token");
    std::fs::read_to_string(&path)
        .map(|s| s.trim().to_string())
        .map_err(|e| format!("could not read {}: {e}", path.display()))
}

/// Whether the daemon unit is up, so the UI can say something useful instead of
/// just failing to connect.
#[tauri::command]
fn daemon_status() -> serde_json::Value {
    let active = std::process::Command::new("systemctl")
        .args(["--user", "is-active", "grokked.service"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim() == "active")
        .unwrap_or(false);
    serde_json::json!({ "unit_active": active })
}

#[tauri::command]
fn start_daemon() -> Result<(), String> {
    std::process::Command::new("systemctl")
        .args(["--user", "start", "grokked.service"])
        .status()
        .map_err(|e| e.to_string())
        .and_then(|s| if s.success() { Ok(()) } else { Err("systemctl start failed".into()) })
}

/// Last 40 journal lines. Debugging a daemon you cannot see is miserable, so the
/// UI puts them one click away.
#[tauri::command]
fn daemon_logs() -> String {
    std::process::Command::new("journalctl")
        .args(["--user", "-u", "grokked", "-n", "40", "--no-pager", "-o", "cat"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).to_string())
        .unwrap_or_else(|e| format!("could not read journal: {e}"))
}

pub fn run() {
    // Serve the frontend over plain http://localhost instead of Tauri's custom
    // scheme. The custom scheme is treated as a secure context, which makes the
    // http://127.0.0.1:16080 noVNC iframe active mixed content -- WebKitGTK
    // blocks it and renders a blank frame with no console message.
    let port = portpicker::pick_unused_port().expect("no free port");

    tauri::Builder::default()
        .plugin(tauri_plugin_localhost::Builder::new(port).build())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_notification::init())
        .invoke_handler(tauri::generate_handler![
            daemon_token,
            daemon_status,
            start_daemon,
            daemon_logs
        ])
        .setup(move |app| {
            // tauri-plugin-localhost's server does not map the bare "/" -- it
            // answers 500 there while serving /index.html and /assets/* fine,
            // which renders as a blank white window with no error anywhere.
            // Ask for index.html explicitly.
            //
            // In dev, point at the vite server instead so HMR works. That is
            // already a plain http://localhost origin, so the mixed-content rule
            // that forces the localhost plugin in release does not apply.
            let url = if cfg!(debug_assertions) {
                option_env!("TAURI_DEV_URL")
                    .unwrap_or("http://localhost:1430")
                    .parse()
                    .unwrap()
            } else {
                format!("http://localhost:{port}/index.html").parse().unwrap()
            };
            WebviewWindowBuilder::new(app, "main", WebviewUrl::External(url))
                .title("Grokked Bot")
                .inner_size(1500.0, 950.0)
                .min_inner_size(1100.0, 700.0)
                .build()?;
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
