use tauri::{WebviewUrl, WebviewWindowBuilder};

/// Where the daemon keeps its token. Must match CONFIG_DIR in
/// packages/daemon/src/config.ts.
fn config_dir() -> Result<std::path::PathBuf, String> {
    let home = std::path::PathBuf::from(std::env::var("HOME").map_err(|e| e.to_string())?);
    Ok(if cfg!(target_os = "macos") {
        home.join("Library/Application Support/Grokked")
    } else {
        home.join(".config/grokked")
    })
}

/// The daemon's bearer token, generated by the daemon on first boot.
/// The UI never stores credentials of its own.
#[tauri::command]
fn daemon_token() -> Result<String, String> {
    let path = config_dir()?.join("token");
    std::fs::read_to_string(&path)
        .map(|s| s.trim().to_string())
        .map_err(|e| format!("could not read {}: {e}", path.display()))
}

#[cfg(target_os = "linux")]
mod daemon {
    /// Whether the daemon unit is up, so the UI can say something useful instead
    /// of just failing to connect.
    pub fn is_running(_app: &tauri::AppHandle) -> bool {
        std::process::Command::new("systemctl")
            .args(["--user", "is-active", "grokked.service"])
            .output()
            .map(|o| String::from_utf8_lossy(&o.stdout).trim() == "active")
            .unwrap_or(false)
    }

    pub fn start(_app: &tauri::AppHandle) -> Result<(), String> {
        std::process::Command::new("systemctl")
            .args(["--user", "start", "grokked.service"])
            .status()
            .map_err(|e| e.to_string())
            .and_then(|s| if s.success() { Ok(()) } else { Err("systemctl start failed".into()) })
    }

    /// Last 40 journal lines. Debugging a daemon you cannot see is miserable, so
    /// the UI puts them one click away.
    pub fn logs() -> String {
        std::process::Command::new("journalctl")
            .args(["--user", "-u", "grokked", "-n", "40", "--no-pager", "-o", "cat"])
            .output()
            .map(|o| String::from_utf8_lossy(&o.stdout).to_string())
            .unwrap_or_else(|e| format!("could not read journal: {e}"))
    }

    pub fn start_on_launch(_app: &tauri::AppHandle) {}
    pub fn stop(_app: &tauri::AppHandle) {}
}

/// macOS has no systemd, and an office Mac user shouldn't have to install a
/// launchd agent by hand. So the app runs the daemon itself: the bundled Node
/// (a sidecar next to the app binary) on the bundled daemon (a resource). The
/// trade-off is that bots stop when the app quits.
#[cfg(not(target_os = "linux"))]
mod daemon {
    use std::io::{Read, Seek, SeekFrom};
    use std::process::{Child, Command, Stdio};
    use std::sync::Mutex;
    use tauri::Manager;

    pub struct Proc(pub Mutex<Option<Child>>);

    fn log_path() -> std::path::PathBuf {
        super::config_dir().unwrap_or_default().join("daemon.log")
    }

    fn port_open() -> bool {
        std::net::TcpStream::connect_timeout(
            &"127.0.0.1:8787".parse().unwrap(),
            std::time::Duration::from_millis(300),
        )
        .is_ok()
    }

    pub fn is_running(app: &tauri::AppHandle) -> bool {
        let state = app.state::<Proc>();
        let mut guard = state.0.lock().unwrap();
        let alive = match guard.as_mut() {
            Some(c) => matches!(c.try_wait(), Ok(None)),
            None => false,
        };
        alive || port_open()
    }

    pub fn start(app: &tauri::AppHandle) -> Result<(), String> {
        if is_running(app) {
            return Ok(());
        }
        let exe = std::env::current_exe().map_err(|e| e.to_string())?;
        let node = exe.parent().ok_or("no exe dir")?.join("node");
        let script = app
            .path()
            .resource_dir()
            .map_err(|e| e.to_string())?
            .join("daemon/grokked.mjs");

        let dir = super::config_dir()?;
        std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
        let log = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(log_path())
            .map_err(|e| e.to_string())?;

        let child = Command::new(&node)
            .arg(&script)
            .env("NODE_ENV", "production")
            .current_dir(&dir)
            .stdin(Stdio::null())
            .stdout(log.try_clone().map_err(|e| e.to_string())?)
            .stderr(log)
            .spawn()
            .map_err(|e| format!("could not start {}: {e}", node.display()))?;
        *app.state::<Proc>().0.lock().unwrap() = Some(child);

        // The UI health-checks right after this returns; give the daemon a moment
        // to bind so "Start daemon" doesn't bounce straight back to the error.
        for _ in 0..50 {
            if port_open() {
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(100));
        }
        Ok(())
    }

    pub fn logs() -> String {
        let mut f = match std::fs::File::open(log_path()) {
            Ok(f) => f,
            Err(e) => return format!("could not read {}: {e}", log_path().display()),
        };
        let len = f.metadata().map(|m| m.len()).unwrap_or(0);
        let _ = f.seek(SeekFrom::Start(len.saturating_sub(8000)));
        let mut s = String::new();
        let _ = f.read_to_string(&mut s);
        s.lines().rev().take(40).collect::<Vec<_>>().into_iter().rev().collect::<Vec<_>>().join("\n")
    }

    pub fn start_on_launch(app: &tauri::AppHandle) {
        if let Err(e) = start(app) {
            eprintln!("daemon did not start: {e}");
        }
    }

    /// SIGTERM, not kill(): the daemon checkpoints SQLite's WAL on the way out.
    pub fn stop(app: &tauri::AppHandle) {
        if let Some(mut c) = app.state::<Proc>().0.lock().unwrap().take() {
            let _ = Command::new("kill").args(["-TERM", &c.id().to_string()]).status();
            for _ in 0..50 {
                if !matches!(c.try_wait(), Ok(None)) {
                    return;
                }
                std::thread::sleep(std::time::Duration::from_millis(100));
            }
            let _ = c.kill();
        }
    }
}

#[tauri::command]
fn daemon_status(app: tauri::AppHandle) -> serde_json::Value {
    serde_json::json!({ "unit_active": daemon::is_running(&app) })
}

#[tauri::command]
fn start_daemon(app: tauri::AppHandle) -> Result<(), String> {
    daemon::start(&app)
}

#[tauri::command]
fn daemon_logs() -> String {
    daemon::logs()
}

pub fn run() {
    // Serve the frontend over plain http://localhost instead of Tauri's custom
    // scheme. The custom scheme is treated as a secure context, which makes the
    // http://127.0.0.1:16080 noVNC iframe active mixed content -- WebKitGTK
    // blocks it and renders a blank frame with no console message.
    let port = portpicker::pick_unused_port().expect("no free port");

    let builder = tauri::Builder::default();
    #[cfg(not(target_os = "linux"))]
    let builder = builder.manage(daemon::Proc(std::sync::Mutex::new(None)));

    builder
        .plugin(tauri_plugin_localhost::Builder::new(port).build())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_clipboard_manager::init())
        .invoke_handler(tauri::generate_handler![
            daemon_token,
            daemon_status,
            start_daemon,
            daemon_logs
        ])
        .setup(move |app| {
            daemon::start_on_launch(app.handle());

            // tauri-plugin-localhost's server does not map the bare "/" -- it
            // answers 500 there while serving /index.html and /assets/* fine,
            // which renders as a blank white window with no error anywhere.
            // Ask for index.html explicitly.
            //
            // In dev, point at the vite server instead so HMR works. That is
            // already a plain http://localhost origin, so the mixed-content rule
            // that forces the localhost plugin in release does not apply.
            let url = if cfg!(debug_assertions) {
                option_env!("TAURI_DEV_URL")
                    .unwrap_or("http://localhost:1430")
                    .parse()
                    .unwrap()
            } else {
                format!("http://localhost:{port}/index.html").parse().unwrap()
            };
            WebviewWindowBuilder::new(app, "main", WebviewUrl::External(url))
                .title("Grokked Bot")
                .inner_size(1500.0, 950.0)
                .min_inner_size(1100.0, 700.0)
                .build()?;
            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|app, event| {
            if let tauri::RunEvent::Exit = event {
                daemon::stop(app);
            }
        });
}
